[package]
name = "date-rs"
version = "0.1.0"
edition = "2021"
authors = ["Luke Sneeringer <luke@sneeringer.com>"]

[dependencies]
diesel = { version = "2", optional = true }

[dev-dependencies]
assert2 = "0.3"

[features]
default = ["diesel-pg"]
diesel-pg = ["dep:diesel", "diesel/postgres"]
