[package]
name = "date-rs"
version = "0.1.0"
edition = "2021"
authors = ["Luke Sneeringer <luke@sneeringer.com>"]
description = "Gregorian calendar date"
rust-version = "1.70"
license = "MIT"
repository = "https://github.com/lukesneeringer/date-rs"
exclude = [
  "/.github/*",
  "/rustfmt.toml",
  "/.prettierrc.yaml",
]

[lib]
name = "date"

[dependencies]
diesel = { version = "2", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
assert2 = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

[features]
default = ["serde"]
diesel-pg = ["dep:diesel", "diesel/postgres"]
