[package]
name = "date-rs"
version = "0.1.2"
edition = "2021"
authors = ["Luke Sneeringer <luke@sneeringer.com>"]
rust-version = "1.70"
license = "Proprietary"
publish = ["ss151w"]
repository = "https://github.com/ss151/date-rs"
documentation = "https://rustdoc.highsignal.tech/date-rs"

[dependencies]
diesel = { version = "2", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
assert2 = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

[features]
default = []
diesel-pg = ["dep:diesel", "diesel/postgres"]
