---
name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install DuckDB.
        run: |
          curl -L https://github.com/duckdb/duckdb/releases/download/v1.3.2/libduckdb-linux-amd64.zip > libduckdb.zip && \
              unzip libduckdb.zip -d libduckdb && \
              sudo mv libduckdb/duckdb.* /usr/local/include && \
              sudo mv libduckdb/libduckdb.so /usr/local/lib && \
              ldconfig -n -v /usr/local/lib && \
              mv /tmp/libduckdb/libduckdb_static.a /tmp/libduckdb/libduckdb.a && \
              ls -al /tmp/libduckdb
        working-directory: /tmp
      - run: cargo test --verbose --all-features --workspace
        env:
          DUCKDB_STATIC: 1
          DUCKDB_LIB_DIR: /tmp/libduckdb
          CARGO_NET_GIT_FETCH_WITH_CLI: true
  lint:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly-slim
    steps:
      - uses: actions/checkout@v4
      - run: rustup +nightly component add rustfmt
      - run: cargo +nightly fmt -- --check
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --no-deps
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
