---
name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opt-nc/setup-duckdb-action@v1.0.14
      - run: cargo test --all-features --workspace
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
  lint:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly-slim
    steps:
      - uses: actions/checkout@v4
      - run: rustup +nightly component add rustfmt
      - run: cargo +nightly fmt -- --check
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --no-deps
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
